### ISSUE TITLE
Records

### ISSUE THREAD

**Issue by r-k-o** [congdm/AyaCompiler#9]
hi,
there seems to be an error -- IdentList ":" type -->    identdef:

                ...

    EventType = RECORD [union]
          KeyEvent   : KEY_EVENT_RECORD;
          MouseEvent : MOUSE_EVENT_RECORD;
          WindowBufferSizeEvent: WINDOW_BUFFER_SIZE_RECORD;
          MenuEvent  : MENU_EVENT_RECORD;
          FocusEvent : FOCUS_EVENT_RECORD
    END;

    INPUT_RECORD = RECORD
          EventType      : WORD; <<<<<<<<<< cause EventType
          pad            : WORD; 
          Event          : EventType
    END;     <<<<< file pos 5159: not type
    PINPUT_RECORD        = POINTER TO INPUT_RECORD;

**Comment by congdm** [comment]
Hi,
Actually, it is not an error, because according to the rule of language: "No identifier may denote more than one object within a given scope". EventType is the culprit here, because it can mean the type EventType, or the field EventType in INPUT_RECORD.
In this case, the field EventType is more local than the type EventType, therefore it is chosen first by the compiler when searching the symbol table, and hence the message "not type".

**Comment by r-k-o** [comment]
thanx for the explanation. up to now i have never found this in any modula i used or old oberon compiler i tried.

**Comment by kekcleader** [comment]
To solve the issue, I would write:
eventType      : WORD
(starting from the small letter)
